DROP TABLE IF EXISTS documents;

CREATE TABLE documents (
    document_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    PRIMARY KEY (document_id),
    document_name VARCHAR(128) NOT NULL,
    document_category VARCHAR(128) NOT NULL,
    document_data BYTEA
);

INSERT INTO documents VALUES ('1','invoice.pdf','finance', '');
INSERT INTO documents VALUES ('2','receipt.png', 'finance', '');
INSERT INTO documents VALUES ('3','contract.pdf', 'contracts', '');